### ISSUE TITLE
Can we use this on v2ray?

### ISSUE THREAD

**Issue by BlurryFlurry** [Haris131/UDP-Custom#1]
I am so sorry I am kind a new to this. Is it possible to make it work with v2ray?

**Comment by Haris131** [comment]
I am sorry, i am just mirroriing file not developer, you can contact
developer udp-custom http://fb.me/eprodevteam

Pada Sabtu, 29 Juni 2024, BlurryFlurry ***@***.***> menulis:

**Comment by Haris131** [comment]
I am sorry, i am just mirroriing file not developer,

Pada Sabtu, 29 Juni 2024, BlurryFlurry ***@***.***> menulis:
